variable "name" {}
variable "subnet_ids" {}
variable "engine" {}
variable "engine_version" {}     
variable "instance_class" {}
variable "db_name" {}       
variable "username" {}  
variable "password" {} 
variable "parameter_group_name" {}
variable "publicly_accessible" {}
variable "storage_type" {}
variable "storage_encrypted" {}
variable "db_subnet_group_name" {}
